export type PersonaCategory =
  | "scientist"
  | "engineer"
  | "devops"
  | "architect"
  | "security"
  | "observer"

export interface AgentPersona {
  name: string
  role: string
  category: PersonaCategory
  color: string
  icon: string
  idleMessage: string
  workingMessages: string[]
  doneMessage: string
  errorMessage: string
  inputs: { id: string; label: string }[]
  outputs: { id: string; label: string }[]
}

export const PERSONAS: Record<string, AgentPersona> = {
  training: {
    name: "Atlas",
    role: "Training Specialist",
    category: "scientist",
    color: "#6d5dfc",
    icon: "FlaskConical",
    idleMessage: "Ready to train...",
    workingMessages: ["Fine-tuning model...", "Computing gradients...", "Optimizing weights..."],
    doneMessage: "Training complete!",
    errorMessage: "Training failed...",
    inputs: [
      { id: "model", label: "model" },
      { id: "dataset", label: "dataset" },
    ],
    outputs: [{ id: "adapter", label: "adapter" }],
  },
  eval: {
    name: "Sage",
    role: "Quality Analyst",
    category: "scientist",
    color: "#eab308",
    icon: "ListChecks",
    idleMessage: "Awaiting evaluation data...",
    workingMessages: ["Running benchmarks...", "Scoring outputs...", "Comparing metrics..."],
    doneMessage: "Evaluation report ready!",
    errorMessage: "Evaluation encountered errors...",
    inputs: [
      { id: "adapter", label: "adapter" },
      { id: "dataset", label: "dataset" },
    ],
    outputs: [{ id: "metrics", label: "metrics" }],
  },
  dataSource: {
    name: "Flux",
    role: "Data Engineer",
    category: "engineer",
    color: "#22c55e",
    icon: "Database",
    idleMessage: "No data loaded yet...",
    workingMessages: ["Streaming records...", "Parsing dataset...", "Validating schema..."],
    doneMessage: "Dataset loaded!",
    errorMessage: "Data loading failed...",
    inputs: [],
    outputs: [{ id: "dataset", label: "dataset" }],
  },
  model: {
    name: "Core",
    role: "Model Architect",
    category: "engineer",
    color: "#3b82f6",
    icon: "Box",
    idleMessage: "Model standing by...",
    workingMessages: ["Loading weights...", "Initializing layers...", "Allocating memory..."],
    doneMessage: "Model ready!",
    errorMessage: "Model failed to load...",
    inputs: [],
    outputs: [{ id: "model", label: "model" }],
  },
  export: {
    name: "Forge",
    role: "Export Engineer",
    category: "devops",
    color: "#ef4444",
    icon: "Download",
    idleMessage: "Waiting for artifact...",
    workingMessages: ["Merging adapter...", "Converting format...", "Compressing weights..."],
    doneMessage: "Export complete!",
    errorMessage: "Export failed...",
    inputs: [{ id: "adapter", label: "adapter" }],
    outputs: [{ id: "artifact", label: "artifact" }],
  },
  serve: {
    name: "Beacon",
    role: "Deployment Lead",
    category: "devops",
    color: "#ec4899",
    icon: "Globe",
    idleMessage: "Endpoint offline...",
    workingMessages: ["Spinning up server...", "Loading model into memory...", "Warming up inference..."],
    doneMessage: "Endpoint live!",
    errorMessage: "Deployment failed...",
    inputs: [{ id: "model", label: "model" }],
    outputs: [{ id: "endpoint", label: "endpoint" }],
  },
  agent: {
    name: "Nexus",
    role: "Agent Architect",
    category: "architect",
    color: "#8b5cf6",
    icon: "MessageSquare",
    idleMessage: "Agent dormant...",
    workingMessages: ["Reasoning over tools...", "Planning next action...", "Executing tool call..."],
    doneMessage: "Agent task complete!",
    errorMessage: "Agent encountered an error...",
    inputs: [{ id: "model", label: "model" }],
    outputs: [{ id: "agent", label: "agent" }],
  },
  router: {
    name: "Switch",
    role: "Traffic Controller",
    category: "architect",
    color: "#f43f5e",
    icon: "Route",
    idleMessage: "No traffic yet...",
    workingMessages: ["Classifying intent...", "Selecting route...", "Distributing requests..."],
    doneMessage: "Routing complete!",
    errorMessage: "Routing failed...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [
      { id: "route_a", label: "route A" },
      { id: "route_b", label: "route B" },
      { id: "fallback", label: "fallback" },
    ],
  },
  prompt: {
    name: "Lyra",
    role: "Prompt Designer",
    category: "observer",
    color: "#06b6d4",
    icon: "FileText",
    idleMessage: "Template ready...",
    workingMessages: ["Composing prompt...", "Injecting variables...", "Formatting output..."],
    doneMessage: "Prompt rendered!",
    errorMessage: "Template error...",
    inputs: [],
    outputs: [{ id: "prompt", label: "prompt" }],
  },
  conditional: {
    name: "Rune",
    role: "Logic Gate",
    category: "observer",
    color: "#f97316",
    icon: "GitBranch",
    idleMessage: "Waiting for metrics...",
    workingMessages: ["Evaluating condition...", "Comparing threshold...", "Branching logic..."],
    doneMessage: "Condition resolved!",
    errorMessage: "Condition evaluation failed...",
    inputs: [{ id: "metrics", label: "metrics" }],
    outputs: [
      { id: "pass", label: "pass" },
      { id: "fail", label: "fail" },
    ],
  },
  rag: {
    name: "Echo",
    role: "Retrieval Specialist",
    category: "engineer",
    color: "#0ea5e9",
    icon: "Search",
    idleMessage: "Index empty...",
    workingMessages: ["Embedding query...", "Searching vectors...", "Assembling context..."],
    doneMessage: "Context retrieved!",
    errorMessage: "Retrieval failed...",
    inputs: [
      { id: "model", label: "model" },
      { id: "data", label: "data" },
    ],
    outputs: [{ id: "output", label: "output" }],
  },
  inference: {
    name: "Pulse",
    role: "Inference Runner",
    category: "observer",
    color: "#a855f7",
    icon: "Zap",
    idleMessage: "Awaiting input...",
    workingMessages: ["Generating tokens...", "Running inference...", "Decoding output..."],
    doneMessage: "Generation complete!",
    errorMessage: "Inference failed...",
    inputs: [
      { id: "model", label: "model" },
      { id: "data", label: "data" },
    ],
    outputs: [{ id: "output", label: "output" }],
  },
  dataGen: {
    name: "Synth",
    role: "Data Synthesizer",
    category: "scientist",
    color: "#14b8a6",
    icon: "Sparkles",
    idleMessage: "Generator idle...",
    workingMessages: ["Synthesizing samples...", "Generating pairs...", "Validating quality..."],
    doneMessage: "Dataset generated!",
    errorMessage: "Generation failed...",
    inputs: [{ id: "agent", label: "agent" }],
    outputs: [{ id: "dataset", label: "dataset" }],
  },
  splitter: {
    name: "Prism",
    role: "Data Splitter",
    category: "engineer",
    color: "#84cc16",
    icon: "Scissors",
    idleMessage: "No data to split...",
    workingMessages: ["Shuffling data...", "Splitting partitions...", "Balancing classes..."],
    doneMessage: "Data split complete!",
    errorMessage: "Split failed...",
    inputs: [{ id: "data", label: "data" }],
    outputs: [
      { id: "train", label: "train" },
      { id: "val", label: "val" },
      { id: "test", label: "test" },
    ],
  },
  mcp: {
    name: "Relay",
    role: "Protocol Bridge",
    category: "architect",
    color: "#7c3aed",
    icon: "Plug",
    idleMessage: "MCP server idle...",
    workingMessages: ["Exposing tools...", "Handling request...", "Serializing response..."],
    doneMessage: "MCP endpoint active!",
    errorMessage: "Protocol error...",
    inputs: [
      { id: "agent", label: "agent" },
      { id: "tools", label: "tools" },
    ],
    outputs: [{ id: "endpoint", label: "endpoint" }],
  },
  a2a: {
    name: "Duo",
    role: "Agent Liaison",
    category: "architect",
    color: "#0891b2",
    icon: "ArrowLeftRight",
    idleMessage: "No agents connected...",
    workingMessages: ["Negotiating handshake...", "Delegating task...", "Awaiting response..."],
    doneMessage: "Collaboration complete!",
    errorMessage: "Agent communication failed...",
    inputs: [
      { id: "agent_a", label: "agent A" },
      { id: "agent_b", label: "agent B" },
    ],
    outputs: [
      { id: "result", label: "result" },
      { id: "transcript", label: "transcript" },
    ],
  },
  gateway: {
    name: "Bastion",
    role: "API Gateway",
    category: "architect",
    color: "#d97706",
    icon: "Network",
    idleMessage: "Gateway offline...",
    workingMessages: ["Configuring routes...", "Applying rate limits...", "Authenticating clients..."],
    doneMessage: "Gateway operational!",
    errorMessage: "Gateway configuration failed...",
    inputs: [
      { id: "agents", label: "agents" },
      { id: "config", label: "config" },
    ],
    outputs: [
      { id: "api", label: "API" },
      { id: "webhook", label: "webhook" },
    ],
  },
  inputGuard: {
    name: "Warden",
    role: "Input Sentinel",
    category: "security",
    color: "#ef4444",
    icon: "ShieldCheck",
    idleMessage: "Guard standing by...",
    workingMessages: ["Scanning input...", "Checking for PII...", "Blocking injection attempt..."],
    doneMessage: "Input cleared!",
    errorMessage: "Threat detected...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
  outputGuard: {
    name: "Cipher",
    role: "Output Sentinel",
    category: "security",
    color: "#f97316",
    icon: "ShieldAlert",
    idleMessage: "Monitoring output...",
    workingMessages: ["Redacting PII...", "Validating schema...", "Checking compliance..."],
    doneMessage: "Output sanitized!",
    errorMessage: "Output violation detected...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
  llmJudge: {
    name: "Themis",
    role: "LLM Judge",
    category: "scientist",
    color: "#8b5cf6",
    icon: "Scale",
    idleMessage: "Awaiting submissions...",
    workingMessages: ["Scoring outputs...", "Comparing criteria...", "Deliberating verdict..."],
    doneMessage: "Judgment rendered!",
    errorMessage: "Judgment failed...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
  abTest: {
    name: "Delta",
    role: "Experiment Lead",
    category: "scientist",
    color: "#ec4899",
    icon: "Split",
    idleMessage: "No experiment running...",
    workingMessages: ["Splitting traffic...", "Collecting metrics...", "Computing significance..."],
    doneMessage: "Winner determined!",
    errorMessage: "Experiment failed...",
    inputs: [
      { id: "model_a", label: "model A" },
      { id: "model_b", label: "model B" },
    ],
    outputs: [{ id: "winner", label: "winner" }],
  },
  cache: {
    name: "Vault",
    role: "Cache Manager",
    category: "engineer",
    color: "#f59e0b",
    icon: "Bolt",
    idleMessage: "Cache cold...",
    workingMessages: ["Checking cache...", "Storing result...", "Evicting stale entries..."],
    doneMessage: "Cache hit!",
    errorMessage: "Cache error...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
  canary: {
    name: "Finch",
    role: "Canary Deploy",
    category: "devops",
    color: "#10b981",
    icon: "Bird",
    idleMessage: "No deployment in progress...",
    workingMessages: ["Rolling out canary...", "Monitoring error rate...", "Comparing performance..."],
    doneMessage: "Canary promoted!",
    errorMessage: "Rollback triggered...",
    inputs: [
      { id: "primary", label: "primary" },
      { id: "canary", label: "canary" },
    ],
    outputs: [{ id: "output", label: "output" }],
  },
  feedback: {
    name: "Vera",
    role: "Feedback Analyst",
    category: "observer",
    color: "#0ea5e9",
    icon: "ThumbsUp",
    idleMessage: "Waiting for feedback...",
    workingMessages: ["Collecting ratings...", "Processing preferences...", "Building DPO pairs..."],
    doneMessage: "Feedback compiled!",
    errorMessage: "Feedback collection failed...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "dpo_data", label: "dpo_data" }],
  },
  tracer: {
    name: "Scope",
    role: "Observability Lead",
    category: "observer",
    color: "#6366f1",
    icon: "Activity",
    idleMessage: "Tracing inactive...",
    workingMessages: ["Recording spans...", "Tracking costs...", "Aggregating latencies..."],
    doneMessage: "Trace exported!",
    errorMessage: "Tracing error...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
  collectTraces: {
    name: "Archivist",
    role: "Trace Collector",
    category: "observer",
    color: "#6366f1",
    icon: "Archive",
    idleMessage: "Waiting for traces...",
    workingMessages: ["Scanning trace database...", "Filtering by rating...", "Collecting relevant traces..."],
    doneMessage: "Traces collected!",
    errorMessage: "Failed to collect traces",
    inputs: [{ id: "trigger", label: "trigger" }],
    outputs: [{ id: "trace_ids", label: "trace_ids" }],
  },
  buildDataset: {
    name: "Curator",
    role: "Dataset Builder",
    category: "engineer",
    color: "#14b8a6",
    icon: "Database",
    idleMessage: "Ready to curate...",
    workingMessages: ["Building training pairs...", "Filtering quality...", "Deduplicating..."],
    doneMessage: "Dataset ready!",
    errorMessage: "Dataset build failed",
    inputs: [{ id: "trace_ids", label: "trace_ids" }],
    outputs: [{ id: "dataset", label: "dataset" }],
  },
  regressionEval: {
    name: "Auditor",
    role: "Regression Checker",
    category: "scientist",
    color: "#f59e0b",
    icon: "ShieldCheck",
    idleMessage: "Standing by for evaluation...",
    workingMessages: ["Comparing models...", "Running eval samples...", "Checking for regressions..."],
    doneMessage: "Evaluation complete!",
    errorMessage: "Regression detected!",
    inputs: [{ id: "model", label: "model" }, { id: "baseline", label: "baseline" }],
    outputs: [{ id: "report", label: "report" }],
  },
  group: {
    name: "Shell",
    role: "Container",
    category: "observer",
    color: "#94a3b8",
    icon: "SquareDashedBottom",
    idleMessage: "Group empty...",
    workingMessages: ["Organizing nodes...", "Updating layout...", "Syncing children..."],
    doneMessage: "Group configured!",
    errorMessage: "Group error...",
    inputs: [{ id: "input", label: "input" }],
    outputs: [{ id: "output", label: "output" }],
  },
}

export const CATEGORY_LABELS: Record<PersonaCategory, string> = {
  scientist: "Scientist",
  engineer: "Engineer",
  devops: "DevOps",
  architect: "Architect",
  security: "Security",
  observer: "Observer",
}
